import { ASSESSMENT_TITLES } from "@/lib/types";
import type { PublicReport } from "./model";

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function line(label: string, value: string | null | undefined): string {
  if (!value) return "";
  return `<p><strong>${escapeHtml(label)}:</strong> ${escapeHtml(value)}</p>`;
}

function list(title: string, items: string[]): string {
  if (items.length === 0) return "";
  return `<h2>${escapeHtml(title)}</h2><ul>${items.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>`;
}

export function reportFileName(report: PublicReport): string {
  const name = (report.product.name || "food-analysis").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  return `${name || "food-analysis"}-report.html`;
}

export function renderPrintableReport(report: PublicReport): string {
  const analysis = report.analysis;
  const product = report.product.name || "Product name not detected";
  const created = new Date(report.createdAt).toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" });
  const nutrition = Object.entries({
    Calories: analysis.nutrition.calories,
    Protein: analysis.nutrition.protein,
    Carbohydrates: analysis.nutrition.carbohydrates,
    Sugar: analysis.nutrition.sugar,
    Fat: analysis.nutrition.fat,
    "Saturated fat": analysis.nutrition.saturatedFat,
    Sodium: analysis.nutrition.sodium,
  })
    .map(([label, value]) => `<li>${escapeHtml(label)}: ${escapeHtml(value || "Not detected")}</li>`)
    .join("");
  const verification = analysis.webVerification?.verified
    ? `<p>${escapeHtml(analysis.webVerification.webFindings || "Web information was found for this product.")}</p>${
        analysis.webVerification.source
          ? `<p>Source: <a href="${escapeHtml(analysis.webVerification.source.url)}">${escapeHtml(analysis.webVerification.source.title)}</a></p>`
          : ""
      }`
    : "<p>Web verification unavailable.</p>";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>xilo-food inspector — Food Analysis Report</title>
  <style>
    body { font-family: Georgia, serif; color: #1c2b22; margin: 2rem auto; max-width: 720px; line-height: 1.5; }
    h1, h2 { font-weight: 600; }
    h1 { font-size: 2rem; margin-bottom: 0.2rem; }
    h2 { font-size: 1.2rem; margin-top: 1.6rem; }
    p, li { font-family: system-ui, sans-serif; font-size: 0.95rem; }
    .muted { color: #5d6b63; }
  </style>
</head>
<body>
  <p class="muted">xilo-food inspector</p>
  <h1>Food Analysis Report</h1>
  <p><strong>${escapeHtml(product)}</strong></p>
  ${line("Brand", report.product.brand)}
  ${line("Created", created)}
  <h2>Analysis</h2>
  <p>${escapeHtml(ASSESSMENT_TITLES[analysis.assessmentStatus])}</p>
  <p>${escapeHtml(analysis.overallAssessment)}</p>
  <p>${escapeHtml(analysis.summary)}</p>
  <h2>Nutrition</h2>
  <ul>${nutrition}</ul>
  ${list("Ingredients", analysis.ingredients)}
  ${list("Concerns", analysis.potentialConcerns.map((item) => `${item.title} — ${item.why}`))}
  ${list("Allergens", analysis.allergensDetected)}
  ${list("Preference notes", analysis.preferenceConflicts)}
  ${list("Positive observations", analysis.positivePoints)}
  <h2>Web verification</h2>
  ${verification}
  <p class="muted">Generated by xilo-food inspector. This report is for informational purposes only and is not a medical diagnosis or medical advice.</p>
</body>
</html>`;
}
